version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: linux
    env:
      - CGO_ENABLED=0
    goos:
      - linux

  - id: pi
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - arm
    goarm:
      - 6

archives:
  - formats:
      - tar.gz
    name_template: >-
      {{ .ProjectName }}
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

nfpms:
  - id: epd-deb
    package_name: epd
    ids:
      - pi
    formats:
      - deb
    vendor: justmiles
    homepage: https://github.com/justmiles/epd
    maintainer: justmiles
    description: Electronic Paper Display daemon with gRPC interface
    license: MIT
    contents:
      - src: packaging/epd.service
        dst: /etc/systemd/system/epd.service
        type: config
      - src: packaging/epd.env
        dst: /etc/default/epd
        type: config|noreplace
    scripts:
      postinstall: packaging/postinstall.sh
      preremove: packaging/preremove.sh

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
