// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: proto/epd.proto

package epdpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DisplayImageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImageData     []byte                 `protobuf:"bytes,1,opt,name=image_data,json=imageData,proto3" json:"image_data,omitempty"` // PNG encoded image data
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisplayImageRequest) Reset() {
	*x = DisplayImageRequest{}
	mi := &file_proto_epd_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisplayImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisplayImageRequest) ProtoMessage() {}

func (x *DisplayImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_epd_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisplayImageRequest.ProtoReflect.Descriptor instead.
func (*DisplayImageRequest) Descriptor() ([]byte, []int) {
	return file_proto_epd_proto_rawDescGZIP(), []int{0}
}

func (x *DisplayImageRequest) GetImageData() []byte {
	if x != nil {
		return x.ImageData
	}
	return nil
}

type DisplayImageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisplayImageResponse) Reset() {
	*x = DisplayImageResponse{}
	mi := &file_proto_epd_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisplayImageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisplayImageResponse) ProtoMessage() {}

func (x *DisplayImageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_epd_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisplayImageResponse.ProtoReflect.Descriptor instead.
func (*DisplayImageResponse) Descriptor() ([]byte, []int) {
	return file_proto_epd_proto_rawDescGZIP(), []int{1}
}

func (x *DisplayImageResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DisplayTextRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisplayTextRequest) Reset() {
	*x = DisplayTextRequest{}
	mi := &file_proto_epd_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisplayTextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisplayTextRequest) ProtoMessage() {}

func (x *DisplayTextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_epd_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisplayTextRequest.ProtoReflect.Descriptor instead.
func (*DisplayTextRequest) Descriptor() ([]byte, []int) {
	return file_proto_epd_proto_rawDescGZIP(), []int{2}
}

func (x *DisplayTextRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type DisplayTextResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisplayTextResponse) Reset() {
	*x = DisplayTextResponse{}
	mi := &file_proto_epd_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisplayTextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisplayTextResponse) ProtoMessage() {}

func (x *DisplayTextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_epd_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisplayTextResponse.ProtoReflect.Descriptor instead.
func (*DisplayTextResponse) Descriptor() ([]byte, []int) {
	return file_proto_epd_proto_rawDescGZIP(), []int{3}
}

func (x *DisplayTextResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ClearRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearRequest) Reset() {
	*x = ClearRequest{}
	mi := &file_proto_epd_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearRequest) ProtoMessage() {}

func (x *ClearRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_epd_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearRequest.ProtoReflect.Descriptor instead.
func (*ClearRequest) Descriptor() ([]byte, []int) {
	return file_proto_epd_proto_rawDescGZIP(), []int{4}
}

type ClearResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearResponse) Reset() {
	*x = ClearResponse{}
	mi := &file_proto_epd_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearResponse) ProtoMessage() {}

func (x *ClearResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_epd_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearResponse.ProtoReflect.Descriptor instead.
func (*ClearResponse) Descriptor() ([]byte, []int) {
	return file_proto_epd_proto_rawDescGZIP(), []int{5}
}

func (x *ClearResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SleepRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SleepRequest) Reset() {
	*x = SleepRequest{}
	mi := &file_proto_epd_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SleepRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SleepRequest) ProtoMessage() {}

func (x *SleepRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_epd_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SleepRequest.ProtoReflect.Descriptor instead.
func (*SleepRequest) Descriptor() ([]byte, []int) {
	return file_proto_epd_proto_rawDescGZIP(), []int{6}
}

type SleepResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SleepResponse) Reset() {
	*x = SleepResponse{}
	mi := &file_proto_epd_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SleepResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SleepResponse) ProtoMessage() {}

func (x *SleepResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_epd_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SleepResponse.ProtoReflect.Descriptor instead.
func (*SleepResponse) Descriptor() ([]byte, []int) {
	return file_proto_epd_proto_rawDescGZIP(), []int{7}
}

func (x *SleepResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_epd_proto protoreflect.FileDescriptor

const file_proto_epd_proto_rawDesc = "" +
	"\n" +
	"\x0fproto/epd.proto\x12\x03epd\"4\n" +
	"\x13DisplayImageRequest\x12\x1d\n" +
	"\n" +
	"image_data\x18\x01 \x01(\fR\timageData\"0\n" +
	"\x14DisplayImageResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"(\n" +
	"\x12DisplayTextRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"/\n" +
	"\x13DisplayTextResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\x0e\n" +
	"\fClearRequest\")\n" +
	"\rClearResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\x0e\n" +
	"\fSleepRequest\")\n" +
	"\rSleepResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\xf3\x01\n" +
	"\n" +
	"EPDService\x12C\n" +
	"\fDisplayImage\x12\x18.epd.DisplayImageRequest\x1a\x19.epd.DisplayImageResponse\x12@\n" +
	"\vDisplayText\x12\x17.epd.DisplayTextRequest\x1a\x18.epd.DisplayTextResponse\x12.\n" +
	"\x05Clear\x12\x11.epd.ClearRequest\x1a\x12.epd.ClearResponse\x12.\n" +
	"\x05Sleep\x12\x11.epd.SleepRequest\x1a\x12.epd.SleepResponseB&Z$github.com/justmiles/epd/proto/epdpbb\x06proto3"

var (
	file_proto_epd_proto_rawDescOnce sync.Once
	file_proto_epd_proto_rawDescData []byte
)

func file_proto_epd_proto_rawDescGZIP() []byte {
	file_proto_epd_proto_rawDescOnce.Do(func() {
		file_proto_epd_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_epd_proto_rawDesc), len(file_proto_epd_proto_rawDesc)))
	})
	return file_proto_epd_proto_rawDescData
}

var file_proto_epd_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_epd_proto_goTypes = []any{
	(*DisplayImageRequest)(nil),  // 0: epd.DisplayImageRequest
	(*DisplayImageResponse)(nil), // 1: epd.DisplayImageResponse
	(*DisplayTextRequest)(nil),   // 2: epd.DisplayTextRequest
	(*DisplayTextResponse)(nil),  // 3: epd.DisplayTextResponse
	(*ClearRequest)(nil),         // 4: epd.ClearRequest
	(*ClearResponse)(nil),        // 5: epd.ClearResponse
	(*SleepRequest)(nil),         // 6: epd.SleepRequest
	(*SleepResponse)(nil),        // 7: epd.SleepResponse
}
var file_proto_epd_proto_depIdxs = []int32{
	0, // 0: epd.EPDService.DisplayImage:input_type -> epd.DisplayImageRequest
	2, // 1: epd.EPDService.DisplayText:input_type -> epd.DisplayTextRequest
	4, // 2: epd.EPDService.Clear:input_type -> epd.ClearRequest
	6, // 3: epd.EPDService.Sleep:input_type -> epd.SleepRequest
	1, // 4: epd.EPDService.DisplayImage:output_type -> epd.DisplayImageResponse
	3, // 5: epd.EPDService.DisplayText:output_type -> epd.DisplayTextResponse
	5, // 6: epd.EPDService.Clear:output_type -> epd.ClearResponse
	7, // 7: epd.EPDService.Sleep:output_type -> epd.SleepResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_epd_proto_init() }
func file_proto_epd_proto_init() {
	if File_proto_epd_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_epd_proto_rawDesc), len(file_proto_epd_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_epd_proto_goTypes,
		DependencyIndexes: file_proto_epd_proto_depIdxs,
		MessageInfos:      file_proto_epd_proto_msgTypes,
	}.Build()
	File_proto_epd_proto = out.File
	file_proto_epd_proto_goTypes = nil
	file_proto_epd_proto_depIdxs = nil
}
