// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.12.4
// source: proto/epd.proto

package epdpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EPDService_DisplayImage_FullMethodName = "/epd.EPDService/DisplayImage"
	EPDService_DisplayText_FullMethodName  = "/epd.EPDService/DisplayText"
	EPDService_Clear_FullMethodName        = "/epd.EPDService/Clear"
	EPDService_Sleep_FullMethodName        = "/epd.EPDService/Sleep"
)

// EPDServiceClient is the client API for EPDService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EPDServiceClient interface {
	// DisplayImage accepts PNG image data and displays it on the EPD
	DisplayImage(ctx context.Context, in *DisplayImageRequest, opts ...grpc.CallOption) (*DisplayImageResponse, error)
	// DisplayText renders text and displays it on the EPD
	DisplayText(ctx context.Context, in *DisplayTextRequest, opts ...grpc.CallOption) (*DisplayTextResponse, error)
	// Clear clears the EPD to white
	Clear(ctx context.Context, in *ClearRequest, opts ...grpc.CallOption) (*ClearResponse, error)
	// Sleep puts the EPD into sleep mode
	Sleep(ctx context.Context, in *SleepRequest, opts ...grpc.CallOption) (*SleepResponse, error)
}

type ePDServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEPDServiceClient(cc grpc.ClientConnInterface) EPDServiceClient {
	return &ePDServiceClient{cc}
}

func (c *ePDServiceClient) DisplayImage(ctx context.Context, in *DisplayImageRequest, opts ...grpc.CallOption) (*DisplayImageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DisplayImageResponse)
	err := c.cc.Invoke(ctx, EPDService_DisplayImage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ePDServiceClient) DisplayText(ctx context.Context, in *DisplayTextRequest, opts ...grpc.CallOption) (*DisplayTextResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DisplayTextResponse)
	err := c.cc.Invoke(ctx, EPDService_DisplayText_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ePDServiceClient) Clear(ctx context.Context, in *ClearRequest, opts ...grpc.CallOption) (*ClearResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClearResponse)
	err := c.cc.Invoke(ctx, EPDService_Clear_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ePDServiceClient) Sleep(ctx context.Context, in *SleepRequest, opts ...grpc.CallOption) (*SleepResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SleepResponse)
	err := c.cc.Invoke(ctx, EPDService_Sleep_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EPDServiceServer is the server API for EPDService service.
// All implementations must embed UnimplementedEPDServiceServer
// for forward compatibility.
type EPDServiceServer interface {
	// DisplayImage accepts PNG image data and displays it on the EPD
	DisplayImage(context.Context, *DisplayImageRequest) (*DisplayImageResponse, error)
	// DisplayText renders text and displays it on the EPD
	DisplayText(context.Context, *DisplayTextRequest) (*DisplayTextResponse, error)
	// Clear clears the EPD to white
	Clear(context.Context, *ClearRequest) (*ClearResponse, error)
	// Sleep puts the EPD into sleep mode
	Sleep(context.Context, *SleepRequest) (*SleepResponse, error)
	mustEmbedUnimplementedEPDServiceServer()
}

// UnimplementedEPDServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEPDServiceServer struct{}

func (UnimplementedEPDServiceServer) DisplayImage(context.Context, *DisplayImageRequest) (*DisplayImageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DisplayImage not implemented")
}
func (UnimplementedEPDServiceServer) DisplayText(context.Context, *DisplayTextRequest) (*DisplayTextResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DisplayText not implemented")
}
func (UnimplementedEPDServiceServer) Clear(context.Context, *ClearRequest) (*ClearResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Clear not implemented")
}
func (UnimplementedEPDServiceServer) Sleep(context.Context, *SleepRequest) (*SleepResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Sleep not implemented")
}
func (UnimplementedEPDServiceServer) mustEmbedUnimplementedEPDServiceServer() {}
func (UnimplementedEPDServiceServer) testEmbeddedByValue()                    {}

// UnsafeEPDServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EPDServiceServer will
// result in compilation errors.
type UnsafeEPDServiceServer interface {
	mustEmbedUnimplementedEPDServiceServer()
}

func RegisterEPDServiceServer(s grpc.ServiceRegistrar, srv EPDServiceServer) {
	// If the following call panics, it indicates UnimplementedEPDServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EPDService_ServiceDesc, srv)
}

func _EPDService_DisplayImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisplayImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EPDServiceServer).DisplayImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EPDService_DisplayImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EPDServiceServer).DisplayImage(ctx, req.(*DisplayImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EPDService_DisplayText_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisplayTextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EPDServiceServer).DisplayText(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EPDService_DisplayText_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EPDServiceServer).DisplayText(ctx, req.(*DisplayTextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EPDService_Clear_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClearRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EPDServiceServer).Clear(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EPDService_Clear_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EPDServiceServer).Clear(ctx, req.(*ClearRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EPDService_Sleep_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SleepRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EPDServiceServer).Sleep(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EPDService_Sleep_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EPDServiceServer).Sleep(ctx, req.(*SleepRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EPDService_ServiceDesc is the grpc.ServiceDesc for EPDService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EPDService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "epd.EPDService",
	HandlerType: (*EPDServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DisplayImage",
			Handler:    _EPDService_DisplayImage_Handler,
		},
		{
			MethodName: "DisplayText",
			Handler:    _EPDService_DisplayText_Handler,
		},
		{
			MethodName: "Clear",
			Handler:    _EPDService_Clear_Handler,
		},
		{
			MethodName: "Sleep",
			Handler:    _EPDService_Sleep_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/epd.proto",
}
